## This is a simple application stochastic gradient decent

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [73]:
data = {
    "Size": [1400, 1600, 1700, 1875, 1100, 1550, 2350, 2450, 1425, 1700],
    "Bedrooms": [3, 3, 4, 2, 2, 3, 4, 4, 3, 3],
    "Price": [245000, 312000, 279000, 308000, 199000, 315000, 479000, 510000, 227000, 380000]
}

df=pd.DataFrame(data)


In [74]:
df

Size  Bedrooms   Price
0  1400         3  245000
1  1600         3  312000
2  1700         4  279000
3  1875         2  308000
4  1100         2  199000
5  1550         3  315000
6  2350         4  479000
7  2450         4  510000
8  1425         3  227000
9  1700         3  380000

In [94]:
X= df.iloc[:,0:2]
Y= df.iloc[:,2]
X=np.array(X,dtype=np.int64)
Y=np.array(Y,dtype=np.int64)

In [95]:
A=np.random.rand(len(X[0]))-0.5
b=np.random.rand(1)-0.5

In [96]:
A,b

(array([-0.39948997, -0.2450646 ]), array([0.3575872]))


# Gradient Derivation for SGD

We minimize the loss function:

$$
L = (Y_{\text{true}} - Y_{\text{pred}})^2
$$

Since 

$$
Y_{\text{pred}} = A \cdot X + b
$$

we compute gradients:


$$
\frac{\partial L}{\partial A} = 2 (Y_{\text{pred}} - Y_{\text{true}}) X
$$


$$
\frac{\partial L}{\partial b} = 2 (Y_{\text{pred}} - Y_{\text{true}})
$$


These gradients update **A** and **b** iteratively to minimize loss.


In [ ]:
for i in range(len(X)):
        Y_pred=np.dot(A,X[i])+b
        A=A+2*alpa*(Y[i]-Y_pred)*X[i] 
        b=b+2*alpa*(Y[i]-Y_pred)
       

In [98]:
A,b

(array([-5.30200646e+52, -9.35646637e+49]), array([-3.11882212e+49]))

In [99]:
np.dot(A,X[0])+b

array([-7.42284024e+55])

In [100]:
Y[0]

245000